Repository JordyHers-org/Times-up-flutter, pull requests merged in 2023-10, with the labels that each got.

#172 Create CODE_OF_CONDUCT.md
  .github/CODE_OF_CONDUCT.md
Labels: hacktoberfest-accepted

#165 Feature/65 implement internet connection logic in case user does not have internet
  lib/app/config/screencontroller_config.dart
  lib/common_widgets/jh_internet_connection_widget.dart
  lib/main_development.dart
  lib/services/internet_connectivity_service.dart
  pubspec.lock
  pubspec.yaml
Labels: hacktoberfest ⛏️, hacktoberfest-accepted

#176 fix(#175) : fix details throwing null exception
  lib/app/pages/child_details_page.dart
  lib/common_widgets/child_horizontal_view.dart
Labels: hacktoberfest-accepted

#174 fix(#13) : fix login issues for Facebook
  android/app/src/development/res/values/strings.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/staging/res/values/strings.xml
Labels: hacktoberfest-accepted

#178 fix(#177) : fix app usage not loading
  lib/app/pages/child_page.dart
  lib/app/pages/set_child_page.dart
  lib/services/database.dart
  test/helpers/test_helpers.mocks.dart
  test/services/firestore_service_test.dart
Labels: review, hacktoberfest-accepted

#179 chore(#128) : send emails to new user upon sign in
  lib/app/landing_page.dart
  lib/models/email_model.dart
  lib/services/api_path.dart
  lib/services/auth.dart
  lib/services/database.dart
  lib/services/firestore_service.dart
  lib/utils/constants.dart
Labels: hacktoberfest-accepted

#180 chore: create a small quickstart section
  README.md
Labels: hacktoberfest-accepted

#182 Merge `dev` into `master`
  .fvm/flutter_sdk
  .fvm/fvm_config.json
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-master.yml
  Makefile
  README.md
  android/app/src/development/res/values/strings.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/res/values/strings.xml
  android/app/src/staging/res/values/strings.xml
  cloudFunctions/.firebaserc
  cloudFunctions/firebase.json
  cloudFunctions/functions/.eslintrc.js
  cloudFunctions/functions/.gitignore
  cloudFunctions/functions/index.js
  cloudFunctions/functions/package-lock.json
  cloudFunctions/functions/package.json
  cloudFunctions/functions/src/index.ts
  cloudFunctions/package-lock.json
  cloudFunctions/package.json
  lib/app/app.dart
  lib/app/config/screencontroller_config.dart
  lib/app/helpers/parsing_extension.dart
  lib/app/landing_page.dart
  lib/app/pages/child_details_page.dart
  lib/app/pages/child_page.dart
  lib/app/pages/parent_page.dart
  lib/app/pages/set_child_page.dart
  lib/common_widgets/child_horizontal_view.dart
  lib/common_widgets/jh_internet_connection_widget.dart
  lib/l10n/arb/app_de.arb
  lib/l10n/arb/app_en.arb
  lib/l10n/arb/app_es.arb
  lib/l10n/arb/app_fr.arb
  lib/l10n/arb/app_tr.arb
  lib/main_development.dart
  lib/main_production.dart
  lib/main_staging.dart
  lib/models/email_model.dart
  lib/services/api_path.dart
  lib/services/auth.dart
  lib/services/database.dart
  lib/services/firestore_service.dart
  lib/services/internet_connectivity_service.dart
  lib/services/notification_service.dart
  lib/utils/constants.dart
  pubspec.lock
  pubspec.yaml
  test/helpers/test_helpers.mocks.dart
  test/services/firestore_service_test.dart
  test/services/notification_service_test.dart
Labels: ready-to-merge

#183 Chore: refactor `Readme` file
  README.md
Labels: review

#181 chore: Removed `flutter_sdk` which is used as a symlink to the flutte…
  .fvm/flutter_sdk
  README.md
Labels: hacktoberfest-accepted

#184 documentation: quick start and run
  README.md
Labels: review, hacktoberfest ⛏️

#192 chore(#124) : replace all Padding occurrences with padding extension
  lib/app/pages/child_details_page.dart
  lib/app/pages/child_page.dart
  lib/app/pages/edit_child_page.dart
  lib/app/pages/notification_page.dart
  lib/app/pages/parent_page.dart
  lib/app/pages/set_child_page.dart
  lib/app/pages/setting_page.dart
  lib/app/splash/splash_content.dart
  lib/app/splash/splash_screen.dart
  lib/common_widgets/bar_chart.dart
  lib/sign_in/email_sign_in_form_bloc_based.dart
  lib/sign_in/email_sign_in_page.dart
  lib/sign_in/phone_sign_bloc_based.dart
  lib/sign_in/phone_sign_in.dart
  lib/sign_in/sign_in_page.dart
  lib/theme/theme.dart
Labels: hacktoberfest-accepted

#207 feat(#203):Displays child name when longpress on child image
  lib/app/pages/child_details_page.dart
  lib/app/pages/parent_page.dart
  lib/common_widgets/child_horizontal_view.dart
  lib/common_widgets/jh_info_row_widget.dart
Labels: hacktoberfest-accepted

#219 Feature/154 revamp app look
  .idea/libraries/Flutter_Plugins.xml
  .idea/runConfigurations/development.xml
  .idea/runConfigurations/production.xml
  .idea/runConfigurations/staging.xml
  android/app/src/main/AndroidManifest.xml
  android/build.gradle
  lib/app/app.dart
  lib/app/config/android_config.dart
  lib/app/features/child_side/child_page.dart
  lib/app/features/parent_side/app_list_page.dart
  lib/app/features/parent_side/child_details_page.dart
  lib/app/features/parent_side/edit_child_page.dart
  lib/app/features/parent_side/notification_page.dart
  lib/app/features/parent_side/parent_page.dart
  lib/app/features/parent_side/setting_page.dart
  lib/app/helpers/parsing_extension.dart
  lib/app/lifecycle/life_cycle.dart
  lib/main_development.dart
  lib/models/notification_model/notification_model.dart
  lib/models/notification_model/notification_model.freezed.dart
  lib/models/notification_model/notification_model.g.dart
  lib/services/database.dart
  lib/services/firestore_service.dart
  lib/theme/theme.dart
  lib/widgets/jh_bar_chart.dart
  lib/widgets/jh_custom_button.dart
  lib/widgets/jh_display_text.dart
  lib/widgets/jh_feature_widget.dart
  lib/widgets/jh_header.dart
  lib/widgets/jh_info_bottom_sheet.dart
  lib/widgets/jh_info_row_widget.dart
  lib/widgets/jh_line_chart.dart
  lib/widgets/jh_no_implementation.dart
  lib/widgets/jh_shimmer_map.dart
  pubspec.lock
  pubspec.yaml
  test/helpers/test_helpers.mocks.dart
  test/services/firestore_service_test.dart
Labels: review

#206 fix(#188): Made child picture not mandatory when adding a new child
  lib/app/features/parent_side/child_details_page.dart
  lib/app/features/parent_side/edit_child_page.dart
Labels: hacktoberfest-accepted

#228 feat(#226) : Implement the possibility to `reset password` in `forgot password` section
  lib/app/features/sign_in/email_sign_in_bloc.dart
  lib/app/features/sign_in/email_sign_in_form_bloc_based.dart
  lib/app/features/sign_in/email_sign_in_model.dart
  lib/services/auth.dart
Labels: hacktoberfest-accepted
