Repository JordyHers-org/Times-up-flutter, pull requests merged in 2023-06, with the labels that each got.

#69 Feature/45 implement makefile to run shell commands
  Makefile
Labels: enhancement

#70 Chore/28 add specific license to project
  LICENSE
Labels: documentation

#77 Bugfix/72 use trailing commas
  analysis_options.yaml
  lib/app/config/geo_full.dart
  lib/app/config/geo_location.dart
  lib/app/landing_page.dart
  lib/app/pages/child_page.dart
  lib/app/pages/edit_child_page.dart
  lib/app/pages/notification_page.dart
  lib/app/pages/parent_page.dart
  lib/app/pages/set_child_page.dart
  lib/app/pages/setting_page.dart
  lib/app/splash/splash_content.dart
  lib/app/splash/splash_screen.dart
  lib/common_widgets/autosize_text.dart
  lib/common_widgets/bar_chart.dart
  lib/common_widgets/child_horizontal_view.dart
  lib/common_widgets/empty_content.dart
  lib/common_widgets/feature_widget.dart
  lib/common_widgets/form_submit_button.dart
  lib/common_widgets/input_dropdown.dart
  lib/common_widgets/list_item_builder.dart
  lib/common_widgets/loading_map.dart
  lib/common_widgets/show_alert_dialog.dart
  lib/common_widgets/show_exeption_alert.dart
  lib/main.dart
  lib/models/child_model.dart
  lib/models/notification_model.dart
  lib/services/api_path.dart
  lib/services/app_usage_local_service.dart
  lib/services/auth.dart
  lib/services/database.dart
  lib/services/geo_locator_service.dart
  lib/services/notification_service.dart
  lib/sign_in/email_sign_in_bloc.dart
  lib/sign_in/email_sign_in_form_bloc_based.dart
  lib/sign_in/email_sign_in_model.dart
  lib/sign_in/phone_sign_bloc_based.dart
  lib/sign_in/sign_in_button.dart
  lib/sign_in/sign_in_page.dart
  lib/sign_in/social_sign_in_button.dart
  lib/theme/theme.dart
  test/custom_raised_button_test.dart
  test/email_sign_in_bloc_test.dart
  test/landing_page_test.dart
  test/sign_in_page_test.dart
Labels: review

#81 chore(#22) : remove the floating action button and replace it with AppBar having a single back button
  lib/app/pages/parent_page.dart
Labels: review, chore-branch

#83 fix(#14) : fixed log out issue
  android/app/google-services.json
  android/build.gradle
  lib/services/auth.dart
  pubspec.lock
Labels: ready-to-merge

#82 fix(#52) : fixes the app loading as well as validator issue
  lib/app/pages/edit_child_page.dart
Labels: ready-to-merge

#90 chore(#61):cleaned pubspec.yaml file
  pubspec.yaml
Labels: ready-to-merge

#91 Test/18 improve tests in the project
  lib/app/config/geo_full.dart
  lib/utils/constants.dart
  pubspec.lock
  pubspec.yaml
  test/app/config/geo_full_test.dart
  test/app/landing_page_test.dart
  test/common_widgets/auto_size_text_test.dart
  test/common_widgets/bar_chart_test.dart
  test/common_widgets/custom_raised_button_test.dart
  test/common_widgets/empty_content_test.dart
  test/common_widgets/feature_widget_test.dart
  test/common_widgets/loading_map_test.dart
  test/common_widgets/show_alert_dialog.dart
  test/email_sign_in_bloc_test.dart
  test/helpers/test_helpers.dart
  test/helpers/test_helpers.mocks.dart
  test/landing_page_test.dart
  test/mocks.dart
  test/models/child_model_test.dart
  test/models/notification_model_test.dart
  test/models/set_child_model_test.dart
  test/services/app_usage_local_service_test.dart
  test/services/app_usage_service_test.dart
  test/services/database_service_test.dart
  test/services/firestore_service_test.dart
  test/services/notification_service_test.dart
  test/services/shared_preference_service_test.dart
  test/sign-in/email_sign_in_bloc_test.dart
  test/sign-in/sign_in_manager_test.dart
  test/sign-in/sign_in_page_test.dart
Labels: review

#96 Bugfix/53 fixed black line on add child page
  lib/app/pages/edit_child_page.dart
Labels: ready-to-merge

#102 Bugfix/97 app usage data are not retrieve when parent register a childs device
  lib/app/pages/child_details_page.dart
  lib/services/app_usage_local_service.dart
Labels: review

#109 fix(#108) : Changed the color of Default action button of all alert dialog box
  lib/common_widgets/show_alert_dialog.dart
Labels: ready-to-merge

#112 bugfix/99-widget-overflow-on-childs-page
  lib/app/pages/child_page.dart
  pubspec.lock
Labels: review

#106 Bugfix/62 use freezed package and json generator to regenerate dtos
  .github/workflows/deploy-dev.yml
  .github/workflows/deploy-master.yml
  .gitignore
  analysis_options.yaml
  lib/app/config/geo_location.dart
  lib/app/helpers/parsing_extension.dart
  lib/app/pages/child_details_page.dart
  lib/app/pages/child_page.dart
  lib/app/pages/edit_child_page.dart
  lib/app/pages/notification_page.dart
  lib/app/pages/parent_page.dart
  lib/app/pages/set_child_page.dart
  lib/models/child_model.dart
  lib/models/child_model/child_model.dart
  lib/models/notification_model.dart
  lib/models/notification_model/notification_model.dart
  lib/models/set_child_model.dart
  lib/services/app_usage_local_service.dart
  lib/services/database.dart
  lib/services/firestore_service.dart
  lib/services/notification_service.dart
  pubspec.lock
  pubspec.yaml
  test/helpers/test_helpers.mocks.dart
  test/mocks.dart
  test/models/child_model_test.dart
  test/models/notification_model_test.dart
  test/services/notification_service_test.dart
Labels: ready-to-merge

#84 enhancement: implement logger the project
  lib/app/config/geo_full.dart
  lib/app/config/geo_location.dart
  lib/app/pages/child_details_page.dart
  lib/app/pages/edit_child_page.dart
  lib/app/pages/notification_page.dart
  lib/app/pages/parent_page.dart
  lib/app/pages/set_child_page.dart
  lib/app/pages/setting_page.dart
  lib/common_widgets/show_logger.dart
  lib/services/app_usage_service.dart
  lib/services/auth.dart
  lib/services/database.dart
  lib/services/firestore_service.dart
  lib/services/notification_service.dart
  lib/sign_in/email_sign_in_bloc.dart
  lib/sign_in/phone_sign_bloc_based.dart
  lib/sign_in/sign_in_page.dart
  pubspec.lock
  pubspec.yaml
Labels: ready-to-merge

#132 Bugfix/131 the font in the app is not responsive
  lib/app/pages/child_details_page.dart
  lib/app/pages/parent_page.dart
  lib/app/splash/splash_content.dart
  lib/common_widgets/jh_display_text.dart
  lib/common_widgets/jh_header.dart
  lib/common_widgets/jh_header_widget.dart
  lib/common_widgets/jh_info_box.dart
  lib/common_widgets/jh_info_row_widget.dart
  lib/common_widgets/jh_summary_tile.dart
  lib/common_widgets/show_alert_dialog.dart
  lib/utils/data.dart
  pubspec.lock
Labels: review

#140 feat(#138) : implements a battery widget.
  lib/app/pages/child_details_page.dart
  lib/common_widgets/jh_battery_widget.dart
  lib/sign_in/validators.dart
  pubspec.lock
Labels: review

#135 Feature/17 calculate and add real time statistics
  lib/app/helpers/parsing_extension.dart
  lib/app/landing_page.dart
  lib/app/lifecycle/life_cycle.dart
  lib/app/pages/child_details_page.dart
  lib/app/pages/child_page.dart
  lib/app/pages/parent_page.dart
  lib/app/pages/set_child_page.dart
  lib/common_widgets/jh_feature_widget.dart
  lib/common_widgets/jh_header_widget.dart
  lib/common_widgets/jh_summary_tile.dart
  lib/main.dart
  lib/services/app_usage_local_service.dart
  lib/services/app_usage_service.dart
  lib/services/database.dart
  lib/services/device_info_service.dart
  pubspec.lock
  pubspec.yaml
  test/services/app_usage_local_service_test.dart
Labels: review
